### Q1 Simulation in Sociology

In [9]:
import scipy.stats as sts
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
#data= sts.norms.rvs(means, std, size)

In [10]:
def inc_sim(profile):

    #set random seed
    np.random.seed(333)

    #create a matrix of lognormally distributed errors, all of the same dimension as number of years* number of simulations
    errors = np.random.lognormal(0, p['stddev'] ,(p['lf_years'], p['num_draws']))
    
    #create an initial matrix of dim (lf_years, num_draws) (same as that of errors)
    ln_inc_mat = np.zeros((p['lf_years'], p['num_draws']))

    #fill the first row of the matrix with simulations for the first year
    ln_inc_mat[0, :] = np.log(p['inc']) + errors[0, :]

    #loop and apply model to the remaining rows
    for t in range(1, p['lf_years']):
        ln_inc_mat[t, :] =       
        (1-p['rho'])*(np.log(['inc'])+ p['g']*(t-2020))+
        p['rho']*ln_inc_mat[t - 1, :]
        +errors[t, : ]

    
    return ln_i



In [11]:
p = {
        'inc'         : 80000,      #starting income
        'stddev'      : 0.13,       #standard deviation
        'rho'         : 0.4,        #persist rate
        'g'           : 0.025,      #growth rate
        'st_year'     : int(2020),  #start year
        'lf_years'    : 40,         #years to live        
        'num_draws'   : 10000       #simulations
    }
    

In [12]:
print(inc_sim(p))

[[1.25011301 1.04311365 0.94017369 ... 0.91957516 1.35123931 1.07905227]
 [0.93599086 0.97899666 1.02275776 ... 1.15438517 1.18797204 1.00495741]
 [1.27597298 1.23453165 0.76511253 ... 0.90142343 0.81793432 0.94869679]
 ...
 [0.98444015 0.94745008 0.8616369  ... 1.00277689 1.09818692 1.145407  ]
 [0.91261614 0.82762157 0.98184183 ... 0.96184627 1.07245518 1.06348209]
 [1.16673196 0.94366777 0.87535866 ... 0.74982951 0.99770358 0.90759846]]


In [ ]:

    #create a matrix of dim (lf_years, num_draws)
    ln_wealth_mat = np.zeros((p['lf_years'], p['num_draws']))

    #fill the matrix
    ln_wealth_mat[0, :] = np.log(p['w0']) + pareto_errors[0, :]

    #loop and apply model
    for t in range(1, p['lf_years']):
        ln_wealth_mat[t, :] = 
        
        (1-p['rho'])*(p['inc'])
        
        ((1 - p['gr']/4) * (np.log(p['w0']) + p['ms'] * (yr)) +
                                p['ir']/4 * ln_wealth_mat[yr - 1, :]  +
                                np.log(p['inc']/1000+(p['inc']/10000*yr)) +
                                pareto_errors[yr, :])


    wealth_mat = np.exp(ln_wealth_mat) #dealing with large numbers so put in terms of 10k's
    return wealth_mat

In [ ]:
plt.hist(wealth_mat[0,:], bins=50)
plt.xlabel("Wealth Distribution")
plt.title("Number of Respondents in Wealth Bins")

### Part d) Changes in Initial Income and Variability

In [ ]:
p = {   'inc'         : 80000,      #starting income
        'stddev'      : 0.13,       #standard deviation
        'rho'         : 0.4,        #persist rate
        'g'           : 0.025,      #growth rate
        'st_year'     : int(2020),  #start year
        'lf_years'    : 40,         #years to live        
        'num_draws'   : 10000       #simulations
    }
    